[package]
name = "arc-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-core = { path = "../arc-core" }
console = { workspace = true }
dialoguer = { workspace = true, features = ["fuzzy-select"] }
fuzzy-matcher = { workspace = true }
libc = { workspace = true }
